# Generated by Django 4.2.7 on 2023-11-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=1000)),
                ('portal_name', models.CharField(max_length=1000)),
                ('data_volume', models.DecimalField(decimal_places=2, default=0, help_text='Data volume in megabytes', max_digits=10)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_portal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Портал',
                'verbose_name_plural': 'Портали',
            },
        ),
    ]
