# Generated by Django 4.2.7 on 2023-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portals'),
    ]

    operations = [
        migrations.AddField(
            model_name='portals',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
